runtime: nodejs14

handlers:
  # Serve all static files in the dist folder
  - url: /
    static_files: dist/angular-cicd/index.html
    upload: dist/angular-cicd/index.html
  - url: /
    static_dir: dist/angular-cicd
